import { Injectable, BadRequestException, ConflictException } from '@nestjs/common';
import { SqliteService } from '../config/sqlite.service';
import { CreateTransactionDto } from '../dto/transaction.dto';
import { Transaction, TransactionType } from './transaction.interface';
import { TransactionsFirestoreService } from './transactions-firestore.service';
@Injectable()
export class TransactionsService {
  constructor(private readonly sqliteService: SqliteService, private readonly transactionsFirestoreService: TransactionsFirestoreService) {}
  private getPreferredStorage(): 'sqlite' { return 'sqlite'; }
  async create(dto: CreateTransactionDto, memberId: string, _userData?: any): Promise<Transaction> { if (this.transactionsFirestoreService.isActive()) return this.transactionsFirestoreService.create(dto, memberId); const db=this.sqliteService.getDatabase(), now=new Date(), id=`transaction-${Date.now()}-${Math.random().toString(36).slice(2)}`, dueDate=dto.type==='borrow'?new Date(now.getTime()+5*86400000):null; db.prepare('INSERT INTO transactions (id, bookId, memberId, type, status, borrowedDate, dueDate, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)').run(id,dto.bookId,memberId,dto.type,dto.type==='borrow'?'active':'completed',dto.type==='borrow'?now.toISOString():null,dueDate?.toISOString()??null,now.toISOString(),now.toISOString()); return this.map(db.prepare('SELECT * FROM transactions WHERE id = ?').get(id)); }
  async findAll(bookId?: string): Promise<any[]> { if (this.transactionsFirestoreService.isActive()) return this.transactionsFirestoreService.findAll(bookId); const db=this.sqliteService.getDatabase(); return (bookId?db.prepare('SELECT * FROM transactions WHERE bookId = ? ORDER BY createdAt DESC').all(bookId):db.prepare('SELECT * FROM transactions ORDER BY createdAt DESC').all()).map((r:any)=>this.map(r)); }
  async findMemberTransactions(memberId:string): Promise<any[]> { if(this.transactionsFirestoreService.isActive())return this.transactionsFirestoreService.findMemberTransactions(memberId); return (this.sqliteService.getDatabase().prepare('SELECT * FROM transactions WHERE memberId = ? ORDER BY createdAt DESC').all(memberId) as any[]).map(r=>this.map(r)); }
  async return(id:string,memberId:string):Promise<Transaction>{if(this.transactionsFirestoreService.isActive())return this.transactionsFirestoreService.returnBook(id,memberId);return this.update(id,memberId,{status:'pending_return_approval',returnDate:new Date().toISOString()});}
  async renew(id:string,memberId:string):Promise<Transaction>{if(this.transactionsFirestoreService.isActive())return this.transactionsFirestoreService.renew(id,memberId);return this.update(id,memberId,{dueDate:new Date(Date.now()+5*86400000).toISOString()});}
  async approveReturn(id:string,_approver:string):Promise<Transaction>{if(this.transactionsFirestoreService.isActive())return this.transactionsFirestoreService.approveReturn(id);return this.update(id,undefined,{status:'completed'});}
  async rejectReturn(id:string,_approver:string,reason?:string):Promise<Transaction>{if(this.transactionsFirestoreService.isActive())return this.transactionsFirestoreService.rejectReturn(id,reason);return this.update(id,undefined,{status:'active',returnDate:null,rejectionReason:reason??null});}
  private update(id:string,memberId:string|undefined,values:any):Transaction{const db=this.sqliteService.getDatabase(), row=db.prepare(`SELECT * FROM transactions WHERE id = ?${memberId?' AND memberId = ?':''}`).get(...(memberId?[id,memberId]:[id])) as any;if(!row)throw new BadRequestException('Transaction not found');db.prepare(`UPDATE transactions SET ${Object.keys(values).map(k=>`${k} = ?`).join(', ')}, updatedAt = ? WHERE id = ?`).run(...Object.values(values),new Date().toISOString(),id);return this.map(db.prepare('SELECT * FROM transactions WHERE id = ?').get(id));}
  private map(r:any):Transaction{return {id:r.id,bookId:r.bookId,memberId:r.memberId,type:r.type as TransactionType,status:r.status,borrowedDate:r.borrowedDate?new Date(r.borrowedDate):undefined,dueDate:r.dueDate?new Date(r.dueDate):undefined,returnDate:r.returnDate?new Date(r.returnDate):undefined,createdAt:new Date(r.createdAt),updatedAt:new Date(r.updatedAt)};}
}
