#!/usr/bin/env bash
# Bring up local Docker endpoints for phone/tablet testing (photo-booth style).
# - Detects LAN IP
# - Points Keycloak hostname + library NEXT_PUBLIC_* at http://{LAN}:ports
# - Adds Keycloak redirect URIs for the LAN frontend
# - Optionally builds the Capacitor shell
#
# Usage (from library-management/):
#   ./scripts/run-mobile-local.sh
#   ./scripts/run-mobile-local.sh --build-only   # env + Capacitor only (stack already up)
#   ./scripts/run-mobile-local.sh --skip-build   # stack + Keycloak only
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
IDENTITY="$(cd "$ROOT/../identity-platform" && pwd)"
LAN_IP="${LIBRARY_LAN_IP:-}"
SKIP_BUILD=0
BUILD_ONLY=0

for arg in "$@"; do
  case "$arg" in
    --skip-build) SKIP_BUILD=1 ;;
    --build-only) BUILD_ONLY=1 ;;
    --help|-h)
      sed -n '1,20p' "$0"
      exit 0
      ;;
  esac
done

if [[ -z "$LAN_IP" ]]; then
  LAN_IP="$("$ROOT/scripts/lan-ip.sh")"
fi

if [[ -z "$LAN_IP" || "$LAN_IP" == "127.0.0.1" ]]; then
  echo "Could not resolve LIBRARY_LAN_IP. Set it explicitly." >&2
  exit 1
fi

export LIBRARY_LAN_IP="$LAN_IP"
WEB_URL="http://${LAN_IP}:3300"
API_URL="http://${LAN_IP}:3301/api"
KC_URL="http://${LAN_IP}:3510"

echo "══════════════════════════════════════════════"
echo " Library mobile — LOCAL mode"
echo " LAN IP:    $LAN_IP"
echo " Web:       $WEB_URL"
echo " API:       $API_URL"
echo " Keycloak:  $KC_URL"
echo "══════════════════════════════════════════════"

# Write / refresh mobile/env.build
mkdir -p "$ROOT/mobile"
cat >"$ROOT/mobile/env.build" <<EOF
# Generated by scripts/run-mobile-local.sh — do not commit
LIBRARY_CONNECTIVITY=local
LIBRARY_LAN_IP=${LAN_IP}
LIBRARY_WEB_PORT=3300
LIBRARY_API_PORT=3301
LIBRARY_KEYCLOAK_PORT=3510
LIBRARY_KEYCLOAK_REALM=library
LIBRARY_KEYCLOAK_CLIENT_ID=library-frontend
LIBRARY_APP_ID=com.librarymanagement.app
LIBRARY_APP_NAME='Library Management'
EOF
echo "Wrote mobile/env.build"

if [[ "$BUILD_ONLY" -eq 0 ]]; then
  echo ""
  echo "→ Starting Keycloak with LAN hostname…"
  (
    cd "$IDENTITY"
    docker compose -f docker-compose.yml -f docker-compose.mobile.yml up -d
  )

  echo "→ Waiting for Keycloak realm…"
  for i in $(seq 1 60); do
    if curl -sf -o /dev/null "$KC_URL/realms/library"; then
      echo "  Keycloak ready"
      break
    fi
    # Also try localhost while KC starts (hostname switch may need a moment)
    if curl -sf -o /dev/null "http://localhost:3510/realms/library" && [[ "$i" -lt 5 ]]; then
      :
    fi
    sleep 2
    if [[ "$i" -eq 60 ]]; then
      echo "Keycloak did not become ready at $KC_URL" >&2
      exit 1
    fi
  done

  echo "→ Ensuring client redirect URIs (via localhost admin API)…"
  # Admin API still reachable on host port even when KC_HOSTNAME is LAN
  KEYCLOAK_URL="http://localhost:3510" \
    "$IDENTITY/scripts/ensure-client-redirects.sh" library "$WEB_URL"

  echo "→ Starting library frontend/backend with LAN NEXT_PUBLIC_* …"
  (
    cd "$ROOT"
    docker compose -f docker-compose.yml -f docker-compose.mobile.yml up -d --force-recreate frontend backend
  )

  echo "→ Smoke checks…"
  sleep 3
  for u in "$WEB_URL" "$API_URL/books" "$KC_URL/realms/library"; do
    code="$(curl -s -o /dev/null -w "%{http_code}" "$u" || echo fail)"
    echo "  $code  $u"
  done
fi

if [[ "$SKIP_BUILD" -eq 0 ]]; then
  echo ""
  echo "→ Building Capacitor shell…"
  chmod +x "$ROOT/mobile/build-mobile.sh"
  # Use full Xcode even if xcode-select still points at Command Line Tools
  if [[ -d /Applications/Xcode.app/Contents/Developer ]]; then
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
  fi
  export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
  (
    cd "$ROOT/mobile"
    ./build-mobile.sh
  )
fi

echo ""
echo "Done. Next steps:"
echo "  1. Phone on same Wi‑Fi — open $WEB_URL in browser (login should work)"
echo "  2. Android Studio → $ROOT/mobile/android → Run on device/tablet"
if [[ -d "$ROOT/mobile/ios/App" ]] && xcodebuild -version >/dev/null 2>&1; then
  echo "  3. Xcode → $ROOT/mobile/ios/App/App.xcworkspace → iPhone or iPad"
else
  echo "  3. iOS: install full Xcode, then re-run ./scripts/run-mobile-local.sh --build-only"
fi
echo "  4. CI artifacts: Actions → Mobile Build (APK + iOS)"
echo ""
echo "Revert desktop Keycloak hostname later:"
echo "  ./scripts/stop-mobile-local.sh"
